/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rd.temp.converter;

import javax.swing.JOptionPane;

import temp.conversion.DegreeType;
import static temp.conversion.DegreeType.CELSIUS;
import static temp.conversion.DegreeType.FAHRENHEIT;
import temp.conversion.FahrenheitToCelsiusStrategy;

import temp.conversion.TempConverter;

/**
 *
 * @author Alex
 */
public class ConversionWindow extends javax.swing.JFrame {

    private static final String NON_NUM_ERROR = "Must be a number";
    private static final String ERROR_TITLE = "Error";

    /**
     * Creates new form ConversionWindow
     */
    TempConverter tempConverter;
    TempConversionService tempService;

    public ConversionWindow() {
        initComponents();
        tempService = new TempConversionService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblTemp = new javax.swing.JLabel();
        txtDegrees = new javax.swing.JTextField();
        lblFrom = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        rdoFahrenheitFrom = new javax.swing.JRadioButton();
        rdoCelsiusFrom = new javax.swing.JRadioButton();
        rdoFahrenheitTo = new javax.swing.JRadioButton();
        rdoCelsiusTo = new javax.swing.JRadioButton();
        btnConvert = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTemp.setText("Temperature in degrees:");

        txtDegrees.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDegrees.setText("0");
        txtDegrees.setToolTipText("");

        lblFrom.setText("From");

        lblTo.setText("To");

        buttonGroup1.add(rdoFahrenheitFrom);
        rdoFahrenheitFrom.setText("Fahrenheit");

        buttonGroup1.add(rdoCelsiusFrom);
        rdoCelsiusFrom.setSelected(true);
        rdoCelsiusFrom.setText("Celsius");

        buttonGroup2.add(rdoFahrenheitTo);
        rdoFahrenheitTo.setSelected(true);
        rdoFahrenheitTo.setText("Fahrenheit");

        buttonGroup2.add(rdoCelsiusTo);
        rdoCelsiusTo.setText("Celsius");

        btnConvert.setText("Convert");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(lblFrom))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTemp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDegrees, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoFahrenheitTo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdoFahrenheitFrom)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTo)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoCelsiusTo)
                                    .addComponent(rdoCelsiusFrom)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnConvert))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTemp)
                            .addComponent(txtDegrees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblFrom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoFahrenheitFrom)
                            .addComponent(rdoCelsiusFrom))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoFahrenheitTo)
                    .addComponent(rdoCelsiusTo))
                .addGap(18, 18, 18)
                .addComponent(btnConvert)
                .addGap(18, 18, 18)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed

        try {
            Integer.parseInt(txtDegrees.getText());
            if (rdoCelsiusFrom.isSelected()) {
                tempService.setFirst(CELSIUS);
            } else {
                tempService.setFirst(FAHRENHEIT);
            }

            if (rdoCelsiusTo.isSelected()) {
                tempService.setSecond(CELSIUS);
            } else {
                tempService.setSecond(FAHRENHEIT);
            }
            tempService.setTempConverter();
            lblResult.setText(Double.toString(tempService.getConversion(Double.parseDouble(txtDegrees.getText()))));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, NON_NUM_ERROR,
                    ERROR_TITLE, JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnConvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversionWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvert;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblTo;
    private javax.swing.JRadioButton rdoCelsiusFrom;
    private javax.swing.JRadioButton rdoCelsiusTo;
    private javax.swing.JRadioButton rdoFahrenheitFrom;
    private javax.swing.JRadioButton rdoFahrenheitTo;
    private javax.swing.JTextField txtDegrees;
    // End of variables declaration//GEN-END:variables
}
